### PR TITLE
What is tilelive?

### PR DESCRIPTION
**Pull request by mapsam**
This updates the README with a little more information about what tilelive actually is, and provides an example.

refs: #183 

cc @rclark @springmeyer @GretaCB

### CODE REVIEW

**Comment by nerik** [comment]
Would be great to see this merged !

**Comment by springmeyer** [comment]
Made a few minor copyedits. @mapsam - looks great, please merge when you are ready.

**Comment by mapsam** [comment]
Thanks @springmeyer!

**Comment by GretaCB** [comment]
This doc is awesome, thanks for pushing it through ! 🙌

**Pull request merged**
